{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "import epanet as epa\n",
    "import epamodule as em\n",
    "import seaborn as sns\n",
    "from cjsbot import CjsBot\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "links = [\"../../networks/c-town/nodes\", \n",
    "         \"../../networks/c-town/links\", \n",
    "         \"../../networks/c-town/rede.inp\", \n",
    "         \"../../networks/c-town/3dim.csv\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "group_links = [[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,\n",
    "         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,\n",
    "         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,\n",
    "         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,\n",
    "         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,\n",
    "         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,\n",
    "         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,\n",
    "         92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,\n",
    "        105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,\n",
    "        118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,\n",
    "        131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143],\n",
    "       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,\n",
    "        157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,\n",
    "        170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182,\n",
    "        183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,\n",
    "        196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208,\n",
    "        209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,\n",
    "        222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234,\n",
    "        235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247,\n",
    "        248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260,\n",
    "        261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,\n",
    "        274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286],\n",
    "       [287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,\n",
    "        300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,\n",
    "        313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,\n",
    "        326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,\n",
    "        339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351,\n",
    "        352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364,\n",
    "        365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377,\n",
    "        378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390,\n",
    "        391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403,\n",
    "        404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416,\n",
    "        417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429]]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "t = np.array([0.01, 0.079,0.115])\n",
    "t_link = [58, 201, 359]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# realV = epa.RealValues(links, t_link, t, dim=3)\n",
    "# realV.getRealValue()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Começando simulação\n"
     ]
    }
   ],
   "source": [
    "net = epa.Rede(links, group_links, t)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1.9633871418834072e-29"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "net.objetivo(net.target)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([0., 0., 0.])"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "net.gradient(net.target)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "def grad_steps(x0, lr=0.001, max_interacoes=100):\n",
    "    try:\n",
    "        dim = len(x0)\n",
    "        x = x0\n",
    "        y = [net.objetivo(x0)]\n",
    "        caminho = [net.get_dist(x0)]\n",
    "        i = 0\n",
    "        values = [x0]\n",
    "        while np.sqrt(sum(net.gradient(x)**2))>0:\n",
    "            increment = np.vectorize(lambda x: 1 if x>0 else -1)\n",
    "            g = increment(net.gradient(x))\n",
    "            x -= lr*g\n",
    "            caminho.append(net.get_dist(x))\n",
    "            y.append(net.objetivo(x)) \n",
    "            values.append(x)\n",
    "            i+=1\n",
    "            if i > max_interacoes:\n",
    "                print(\"Excedeu as interações limite\")\n",
    "                break\n",
    "            if sum(x<0):\n",
    "                print(\"Escapou do intervalo de confiança\")\n",
    "                break\n",
    "    finally:\n",
    "        net.restart()\n",
    "        return values[y.index(min(y))], y, caminho"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "def calc_centroide(vetor_pontos):\n",
    "    tamanho = vetor_pontos.shape[0]\n",
    "    v = []\n",
    "    for i in range(vetor_pontos.shape[1]):\n",
    "        v.append(vetor_pontos[:,i].sum()/tamanho)\n",
    "    return v"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "# values = np.random.random((100,3))*0.2 +0.001\n",
    "# arq = open(\"teste3/teste3.txt\", 'w')\n",
    "# np.savetxt(arq, values)\n",
    "# arq.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "arq = open(\"teste3/teste3.txt\")\n",
    "values = np.loadtxt(arq)\n",
    "arq.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "net.restart()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:16:45,673 - apscheduler.scheduler - INFO - Scheduler started\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:16:47,670 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:16:47,671 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:16:53,303 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:16:53,304 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:16:59,855 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:16:59,857 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:17:07,832 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:17:07,835 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:17:15,112 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:17:15,113 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:17:17,458 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:17:20,183 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:17:26,685 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:17:26,685 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:17:38,766 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:17:38,767 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:17:49,343 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:17:54,740 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:17:55,750 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:17:55,758 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:18:24,756 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:18:27,514 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:18:43,448 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:18:43,450 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:19:00,862 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:19:04,895 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:19:26,590 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:19:26,591 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:19:38,669 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:19:48,072 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:20:01,199 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:20:01,200 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:20:18,748 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:20:22,706 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:20:35,812 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:20:35,815 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:20:54,126 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:20:57,418 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:21:10,418 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:21:10,421 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:21:26,874 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:21:32,029 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:21:45,028 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:21:45,029 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:22:01,333 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:22:06,638 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:22:19,618 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:22:19,623 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:22:36,429 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:22:41,128 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:22:54,149 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:22:54,155 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:23:11,366 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:23:11,969 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:23:28,758 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:23:28,759 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:23:42,558 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:23:50,365 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:24:03,369 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:24:03,370 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:24:20,344 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:24:22,113 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:24:37,980 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:24:37,981 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:24:56,042 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:25:01,827 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:25:12,459 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:25:12,459 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:25:30,912 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:25:34,097 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:25:47,100 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:25:47,101 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:26:06,893 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:26:08,707 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:26:21,709 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:26:21,710 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:26:38,475 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:26:43,315 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:26:56,225 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:26:56,226 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:27:13,136 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:27:17,826 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:27:30,828 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:27:30,828 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:27:46,704 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:27:52,439 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:28:05,440 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:28:05,440 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:28:22,358 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:28:27,049 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:28:39,958 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:28:39,959 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:28:57,476 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:29:01,554 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:29:14,559 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:29:14,559 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:29:31,678 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:29:36,168 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:29:49,168 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:29:49,169 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:30:07,220 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:30:10,781 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:30:23,780 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:30:23,781 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:30:39,457 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:30:45,388 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:30:58,392 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:30:58,394 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:31:16,751 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:31:19,882 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:31:32,933 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:31:32,934 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:31:49,753 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:31:54,612 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:32:07,510 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:32:07,512 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:32:23,896 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:32:29,040 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:32:42,071 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:32:42,072 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:33:00,959 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:33:03,637 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:33:16,636 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:33:16,637 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:33:34,940 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:33:38,126 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:33:51,250 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:33:51,251 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:34:08,978 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:34:12,741 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:34:25,887 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:34:25,888 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:34:45,466 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:34:47,565 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:35:00,471 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:35:00,472 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:35:18,784 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:35:22,080 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:35:35,026 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:35:35,028 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:35:51,145 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:35:56,688 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:36:09,586 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:36:09,588 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:36:25,314 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:36:31,096 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:36:44,066 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:36:44,068 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:37:18,603 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:37:18,603 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:37:21,651 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:37:29,840 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:37:53,114 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:37:53,120 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:38:00,463 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:38:04,381 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:38:27,726 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:38:27,727 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:38:36,781 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:38:38,964 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:39:02,335 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:39:02,336 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:39:08,294 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:39:13,601 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:39:36,945 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:39:36,947 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:39:44,800 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:39:48,215 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:40:11,424 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:40:11,426 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:40:29,498 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:40:32,963 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:40:46,065 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:40:46,066 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:41:03,005 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:41:07,678 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:41:20,680 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:41:20,681 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:41:36,875 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:41:42,281 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:41:55,289 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:41:55,293 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:42:12,637 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:42:16,904 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:42:29,908 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:42:29,909 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:42:46,178 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:42:51,410 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:43:04,399 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:43:04,400 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:43:20,926 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:43:26,027 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:43:39,027 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:43:39,040 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:43:58,152 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:44:06,296 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:44:13,584 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:44:13,587 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:44:36,648 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:44:45,472 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:44:48,153 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:44:48,154 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:45:20,258 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:45:22,769 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:45:23,777 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:45:23,780 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 465, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/ext/updater.py\", line 416, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"<decorator-gen-156>\", line 2, in get_updates\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 135, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 2638, in get_updates\n",
      "    result = self._post(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/bot.py\", line 245, in _post\n",
      "    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 349, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/home/augusto/.local/lib/python3.8/site-packages/telegram/utils/request.py\", line 276, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "2021-01-06 19:45:56,846 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:46:05,782 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:46:37,119 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:46:37,823 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:47:06,993 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:47:09,478 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:47:40,260 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:47:41,214 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:48:11,175 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:48:13,073 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:48:45,996 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:48:53,735 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:49:23,754 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:49:25,580 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:50:05,916 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:50:07,876 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:50:37,445 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:50:39,985 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:51:19,839 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:51:22,089 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:51:56,617 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:52:04,202 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:52:38,342 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:52:46,290 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:53:17,669 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:53:18,374 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:53:54,419 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:54:00,533 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:54:31,998 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:54:32,603 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:55:11,735 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:55:14,675 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:55:47,128 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:55:56,542 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:56:28,118 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:56:28,626 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:57:00,442 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:57:00,661 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:57:32,626 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:57:42,648 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:58:15,131 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:58:25,247 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:58:56,849 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:58:57,354 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 19:59:29,839 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 19:59:39,594 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:00:11,192 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:00:11,700 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:00:47,922 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:00:53,515 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:01:26,862 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:01:35,615 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:02:07,999 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:02:17,500 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:02:48,670 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:02:49,578 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:03:22,734 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:03:31,928 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:04:02,971 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:04:03,975 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:04:37,568 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:04:46,392 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:05:18,072 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:05:18,480 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:05:52,261 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:06:00,426 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:06:33,092 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:06:42,310 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:07:14,706 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:07:24,309 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:07:56,492 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:08:06,386 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:08:37,573 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:08:38,478 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:09:10,401 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:09:20,389 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:09:51,646 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:09:52,453 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:10:25,266 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:10:34,970 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:11:07,887 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:11:16,923 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:11:50,166 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:11:58,839 - apscheduler.scheduler - INFO - Scheduler started\n",
      "2021-01-06 20:12:34,281 - apscheduler.scheduler - INFO - Scheduler has been shut down\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Excedeu as interações limite\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-01-06 20:12:41,028 - apscheduler.scheduler - INFO - Scheduler started\n"
     ]
    }
   ],
   "source": [
    "bot = CjsBot()\n",
    "pontos = []\n",
    "pontos_y = []\n",
    "inicio = time.time()\n",
    "for i in range(values.shape[0]):\n",
    "    try:\n",
    "        x, y, caminho = grad_steps(values[i,:])\n",
    "        pontos.append(x)\n",
    "        pontos_y.append(net.objetivo(x))\n",
    "        bot.add_commandMessage('status', f\"Posição: {i}\")\n",
    "        #bot.create_commandMessage('tempo', f\"Tempo utilizado: \\n{time.strftime('%H horas %M minutos e %S segundos',time.gmtime(time.time()-inicio) )}\")\n",
    "        bot.start()\n",
    "    except:\n",
    "        continue\n",
    "pontos = np.array(pontos)\n",
    "pontos_y = np.array(pontos_y)\n",
    "centroide_c = calc_centroide(pontos)\n",
    "\n",
    "bot.send_message(f\"\"\"\n",
    "A simulação acabou:\n",
    "Target: {net.target}\n",
    "Centroide: {centroide_c}\n",
    "Distância entre centroide e target: {net.get_dist(centroide_c)}\n",
    "\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "arq = open(\"teste1/result.txt\", 'w')\n",
    "np.savetxt(arq, pontos)\n",
    "arq.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "centroide_c"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "bot.send_message(f\"\"\"\n",
    "A simulação acabou:\n",
    "Target: {net.target}\n",
    "Centroide: {centroide_c}\n",
    "Distância entre centroide e target: {net.get_dist(centroide_c)}\n",
    "\n",
    "\"\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.DataFrame(pontos, columns=['g1','g2','g3'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>g1</th>\n",
       "      <th>g2</th>\n",
       "      <th>g3</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0.015063</td>\n",
       "      <td>0.069133</td>\n",
       "      <td>0.103791</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>0.018097</td>\n",
       "      <td>0.066613</td>\n",
       "      <td>0.102498</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>0.001436</td>\n",
       "      <td>0.094724</td>\n",
       "      <td>0.130576</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>0.063969</td>\n",
       "      <td>0.034395</td>\n",
       "      <td>0.068373</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0.055917</td>\n",
       "      <td>0.055752</td>\n",
       "      <td>0.098119</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>95</th>\n",
       "      <td>0.022236</td>\n",
       "      <td>0.060806</td>\n",
       "      <td>0.096117</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>96</th>\n",
       "      <td>0.026146</td>\n",
       "      <td>0.056878</td>\n",
       "      <td>0.090209</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>97</th>\n",
       "      <td>0.019742</td>\n",
       "      <td>0.065128</td>\n",
       "      <td>0.100015</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>98</th>\n",
       "      <td>-0.000554</td>\n",
       "      <td>0.088814</td>\n",
       "      <td>0.149635</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>99</th>\n",
       "      <td>0.018107</td>\n",
       "      <td>0.068215</td>\n",
       "      <td>0.103111</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>100 rows × 3 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "          g1        g2        g3\n",
       "0   0.015063  0.069133  0.103791\n",
       "1   0.018097  0.066613  0.102498\n",
       "2   0.001436  0.094724  0.130576\n",
       "3   0.063969  0.034395  0.068373\n",
       "4   0.055917  0.055752  0.098119\n",
       "..       ...       ...       ...\n",
       "95  0.022236  0.060806  0.096117\n",
       "96  0.026146  0.056878  0.090209\n",
       "97  0.019742  0.065128  0.100015\n",
       "98 -0.000554  0.088814  0.149635\n",
       "99  0.018107  0.068215  0.103111\n",
       "\n",
       "[100 rows x 3 columns]"
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>g1</th>\n",
       "      <th>g2</th>\n",
       "      <th>g3</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>100.000000</td>\n",
       "      <td>100.000000</td>\n",
       "      <td>100.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>0.032096</td>\n",
       "      <td>0.065269</td>\n",
       "      <td>0.093530</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>0.026867</td>\n",
       "      <td>0.029392</td>\n",
       "      <td>0.025558</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>-0.000771</td>\n",
       "      <td>0.010709</td>\n",
       "      <td>0.034098</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>0.015384</td>\n",
       "      <td>0.051042</td>\n",
       "      <td>0.079957</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>0.022334</td>\n",
       "      <td>0.063196</td>\n",
       "      <td>0.097139</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>0.044219</td>\n",
       "      <td>0.072410</td>\n",
       "      <td>0.105518</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>0.096913</td>\n",
       "      <td>0.195776</td>\n",
       "      <td>0.152323</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "               g1          g2          g3\n",
       "count  100.000000  100.000000  100.000000\n",
       "mean     0.032096    0.065269    0.093530\n",
       "std      0.026867    0.029392    0.025558\n",
       "min     -0.000771    0.010709    0.034098\n",
       "25%      0.015384    0.051042    0.079957\n",
       "50%      0.022334    0.063196    0.097139\n",
       "75%      0.044219    0.072410    0.105518\n",
       "max      0.096913    0.195776    0.152323"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<seaborn.axisgrid.FacetGrid at 0x7fe699fc9f40>"
      ]
     },
     "execution_count": 31,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAWAAAAFgCAYAAACFYaNMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8li6FKAAASs0lEQVR4nO3df6zld13n8eeLTmsrBTuNl+4wnaaADdolcUouFVtiEHAdi2tBRbZx2W6COzVaA6JuiGaz5Y9NTLYIWbPpMkBlQGTpQll+qNXaLbIEtjDtDmWaVhEs7bSTzq2GbdndgG3f+8f51r0O8+PM3Ps973PveT6Sb8735/m+P/ecvOY7n++Pk6pCkjR7z+guQJIWlQEsSU0MYElqYgBLUhMDWJKabOkuYBq7du2qW265pbsMSTqRnMzKG+II+NFHH+0uQZLW3YYIYEnajEYL4CRnJvlCki8luSfJ24b51yV5KMn+YbhirBokaZ6N2Qf8LeAVVfXNJKcDn03yx8Oyd1TV9SPuW5Lm3mgBXJN7nL85TJ4+DN73LEmDUfuAk5yWZD9wGLi1qu4YFl2b5O4kNybZeoxtdyfZl2TfysrKmGVKUotRA7iqnqyqncD5wKVJXgTcALwA2AkcAt5+jG33VNVyVS0vLS2NWaYktZjJVRBV9Q3g08CuqnpkCOangHcDl86iBkmaN2NeBbGU5Jxh/CzgVcB9SbatWu21wIGxapCkeTbmVRDbgL1JTmMS9DdV1aeSfCDJTiYn5O4HrhmxBkmaW2NeBXE3cMlR5r9hrH1K0kbinXCS1MQAlqQmBrAkNTGAR7Z9xwUkaR+277ig+08h6Qgb4nnAG9nDBx/k9e/6XHcZfPiay7pLkHQEj4AlqYkBLElNDGBJamIAS1ITA1iSmhjAktTEAJakJgawJDUxgCWpiQEsSU0MYElqYgBLUhMDWJKaGMCS1MQAlqQmBrAkNTGAJamJASxJTQxgSWpiAEtSEwNYkpoYwJLUxACWpCYGsCQ1MYAlqYkBLElNDGBJamIAS1ITA1iSmowWwEnOTPKFJF9Kck+Stw3zz01ya5KvDK9bx6pBkubZmEfA3wJeUVU/COwEdiV5KfBW4Laqugi4bZiWpIUzWgDXxDeHydOHoYArgb3D/L3Aa8aqQZLm2ah9wElOS7IfOAzcWlV3AOdV1SGA4fU5x9h2d5J9SfatrKyMWaYktRg1gKvqyaraCZwPXJrkRSex7Z6qWq6q5aWlpfGKlKQmM7kKoqq+AXwa2AU8kmQbwPB6eBY1SNK8GfMqiKUk5wzjZwGvAu4DPgFcPax2NfDxsWqQpHm2ZcT33gbsTXIak6C/qao+leTzwE1J3gg8ALxuxBokaW6NFsBVdTdwyVHm/w3wyrH2K0kbhXfCSVITA1iSmhjAktTEAJakJgawJDUxgCWpiQEsSU0MYElqYgBLUhMDWJKaGMCS1MQAlqQmBrAkNTGAJamJASxJTQxgSWpiAEtSEwNYkpoYwJLUxACWpCYGsCQ1MYAlqYkBLElNDGBJamIAS1ITA1iSmhjAktTEAJakJgawJDUxgCWpiQEsSU0MYElqYgBLUhMDWJKajBbASXYkuT3JvUnuSfKmYf51SR5Ksn8YrhirBkmaZ1tGfO8ngF+rqruSPAu4M8mtw7J3VNX1I+5bkubeaAFcVYeAQ8P440nuBbaPtT9J2mhm0gec5ELgEuCOYda1Se5OcmOSrbOoQZLmzegBnORs4KPAm6vqMeAG4AXATiZHyG8/xna7k+xLsm9lZWXsMiVp5kYN4CSnMwnfD1bVzQBV9UhVPVlVTwHvBi492rZVtaeqlqtqeWlpacwyJanFmFdBBHgvcG9V/c6q+dtWrfZa4MBYNUjSPBvzKojLgTcAX06yf5j3m8BVSXYCBdwPXDNiDZI0t8a8CuKzQI6y6I/G2qckbSTeCSdJTQxgSWpiAEtSEwNYkpoYwJLUxACWpCYGsCQ1MYAlqYkBLElNDGBJamIAS1ITA1iSmhjAktTEAJakJgawJDUxgCWpiQEsSU0MYElqYgBLUhMDWJKaGMCS1MQAlqQmBrAkNTGAJamJASxJTQxgSWpiAEtSEwNYkpoYwJLUxACWpCYGsCQ1MYAlqYkBLElNDGBJajJaACfZkeT2JPcmuSfJm4b55ya5NclXhtetY9UgSfNszCPgJ4Bfq6ofAF4K/HKSi4G3ArdV1UXAbcO0JC2c0QK4qg5V1V3D+OPAvcB24Epg77DaXuA1Y9UgSfNsJn3ASS4ELgHuAM6rqkMwCWngObOoQZLmzegBnORs4KPAm6vqsZPYbneSfUn2raysjFegJDUZNYCTnM4kfD9YVTcPsx9Jsm1Yvg04fLRtq2pPVS1X1fLS0tKYZUpSizGvggjwXuDeqvqdVYs+AVw9jF8NfHysGiRpnm0Z8b0vB94AfDnJ/mHebwK/DdyU5I3AA8DrRqxBkubWaAFcVZ8FcozFrxxrv5K0UXgnnCQ1mSqAk1w+zTxJ0vSmPQL+3SnnSZKmdNw+4CQ/DFwGLCV5y6pFzwZOG7Ow9bB9xwU8fPDB7jIk6ahOdBLuDODsYb1nrZr/GPCzYxW1Xh4++CCvf9fnWmv48DWXte5f0vw6bgBX1Z8Df57kfVX19RnVJEkLYdrL0L4ryR7gwtXbVNUrxihKkhbBtAH8X4D/BLwHeHK8ciRpcUwbwE9U1Q2jViJJC2bay9A+meSXkmwbftHi3CTnjlqZJG1y0x4BP/3wnN9YNa+A569vOZK0OKYK4Kp63tiFSNKimSqAk/yLo82vqvevbzmStDim7YJ4yarxM5k8zewuwACWpFM0bRfEr6yeTvI9wAdGqUiSFsSpPo7y/wAXrWchkrRopu0D/iSTqx5g8hCeHwBuGqsoSVoE0/YBX79q/Ang61V1cIR6JGlhTNUFMTyU5z4mT0TbCnx7zKIkaRFM+4sYPwd8gckPaP4ccEeSuX8cpSTNs2m7IH4LeElVHQZIsgT8GfCRsQrTOnvGFpJj/Ubq7Dz3/B089OAD3WVIc2HaAH7G0+E7+Bv8Qc+N5akn2h9ODz6gXlpt2gC+JcmfAB8apl8P/NE4JUnSYjjRb8J9H3BeVf1Gkp8GXgYE+DzwwRnUJ0mb1om6Ed4JPA5QVTdX1Vuq6leZHP2+c+ziJGkzO1EAX1hVdx85s6r2Mfl5IknSKTpRAJ95nGVnrWchkrRoThTAX0zyr46cmeSNwJ3jlCRJi+FEV0G8GfhYkp/n/wfuMnAG8NoxC5Okze64AVxVjwCXJflR4EXD7D+sqv82emWStMlN+zzg24HbR65FkhaKd7NJUhMDWJKaGMCS1GS0AE5yY5LDSQ6smnddkoeS7B+GK8bavyTNuzGPgN8H7DrK/HdU1c5h8IE+khbWaAFcVZ8B/nas95ekja6jD/jaJHcPXRRbG/YvSXNh1gF8A/ACYCdwCHj7sVZMsjvJviT7VlZWZlWfJM3MTAO4qh6pqier6ing3cClx1l3T1UtV9Xy0tLS7IqUpBmZaQAn2bZq8rXAgWOtK0mb3bQ/SXTSknwIeDnwvUkOAv8WeHmSnUAB9wPXjLV/SZp3owVwVV11lNnvHWt/krTReCecJDUxgCWpiQEsSU0MYElqYgBLUhMDWJKaGMCS1MQAlqQmBrAkNTGAJamJASxJTQxgSWpiAEtSEwNYkpoYwJLUxACWpCYGsCQ1MYAlqYkBLElNDGBJamIAS1ITA1iSmhjAktTEAJakJgawJDUxgCWpiQEsSU0MYElqYgBLUhMDWJKaGMCS1MQAlqQmBrAkNTGAJanJaAGc5MYkh5McWDXv3CS3JvnK8Lp1rP1L0rwb8wj4fcCuI+a9Fbitqi4CbhumJWkhjRbAVfUZ4G+PmH0lsHcY3wu8Zqz9S9K8m3Uf8HlVdQhgeH3OjPcvSXNjbk/CJdmdZF+SfSsrK93lSNK6m3UAP5JkG8DwevhYK1bVnqparqrlpaWlmRUoSbMy6wD+BHD1MH418PEZ71+S5saYl6F9CPg88MIkB5O8Efht4MeSfAX4sWFakhbSlrHeuKquOsaiV461T0naSOb2JJwkbXYGsCQ1MYAlqYkBLElNDGBJamIAS1ITA1iSmhjAktTEAJakJgawJDUxgCWpiQEsSU0MYElqYgBLUhMDWJKaGMCS1MQAlqQmBrAkNTGAJamJASxJTQxgSWpiAEuNtu+4gCTtw/YdF3T/KYDF+3uM9rP0kk7s4YMP8vp3fa67DD58zWXdJQCL9/fwCFiSmhjAktTEAJakJgawJDUxgCWpiQEsSU28DE2z9YwtJOmugueev4OHHnygu4z5MSefy6IxgDVbTz2xUNd5bhh+Li3sgpCkJgawJDUxgCWpiQEsSU1aTsIluR94HHgSeKKqljvqkKROnVdB/GhVPdq4f0lqZReEJDXpCuAC/jTJnUl2H22FJLuT7Euyb2VlZcblSdL4ugL48qp6MfATwC8n+ZEjV6iqPVW1XFXLS0tLs69QkkbWEsBV9fDwehj4GHBpRx2S1GnmAZzkmUme9fQ48E+AA7OuQ5K6dVwFcR7wseHBH1uAP6iqWxrqkKRWMw/gqvoa8IOz3q8kzRsvQ5OkJgawJDXxecBaTD6AXHPAANZi8gHkmgN2QUhSEwNYkpoYwJLUxACWpCYGsCQ1MYAlqYkBLElNDGBJamIAS1ITA1iSmhjAktTEAJakJgawJDUxgCWpiQEsSU0MYElqYgBLUhMDWJKaGMCS1MQAlqQmBrAkNTGAJamJASxJTQxgSWpiAEtSEwNYkpoYwJLUxACWpCYGsCQ1MYAlqUlLACfZleQvkvxVkrd21CBJ3WYewElOA/4j8BPAxcBVSS6edR2S1K3jCPhS4K+q6mtV9W3gPwNXNtQhSa1SVbPdYfKzwK6q+oVh+g3AD1XVtUestxvYPUy+EPiLNez2e4FH17D9PNvMbYPN3b7N3DZYzPY9WlW7pn2DLetbz1RylHnf8a9AVe0B9qzLDpN9VbW8Hu81bzZz22Bzt28ztw1s3zQ6uiAOAjtWTZ8PPNxQhyS16gjgLwIXJXlekjOAfwZ8oqEOSWo18y6IqnoiybXAnwCnATdW1T0j73ZdujLm1GZuG2zu9m3mtoHtO6GZn4STJE14J5wkNTGAJanJhg7gE93SnIn/MCy/O8mLp912Hpxq+5LsSHJ7knuT3JPkTbOv/vjW8tkNy09L8j+TfGp2VU9vjd/Nc5J8JMl9w2f4w7Ot/vjW2LZfHb6TB5J8KMmZs63+xKZo3/cn+XySbyX59ZPZ9jtU1YYcmJzA+yrwfOAM4EvAxUescwXwx0yuPX4pcMe023YPa2zfNuDFw/izgL+cp/atpW2rlr8F+APgU93tWe/2AXuBXxjGzwDO6W7TOn0vtwN/DZw1TN8E/MvuNp1C+54DvAT4d8Cvn8y2Rw4b+Qh4mluarwTeXxP/AzgnybYpt+12yu2rqkNVdRdAVT0O3Mvkyz8v1vLZkeR84NXAe2ZZ9Ek45fYleTbwI8B7Aarq21X1jVkWfwJr+uyYXHl1VpItwHczf/cAnLB9VXW4qr4I/N3JbnukjRzA24EHV00f5DtD5ljrTLNtt7W07+8luRC4BLhj3Ss8dWtt2zuBfw08NVaBa7SW9j0fWAF+b+hieU+SZ45Z7Ek65bZV1UPA9cADwCHgf1XVn45Y66lYSzac9LYbOYCnuaX5WOtMdTt0s7W0b7IwORv4KPDmqnpsHWtbq1NuW5KfBA5X1Z3rX9a6WctntwV4MXBDVV0C/G9gns5RrOWz28rkiPB5wHOBZyb55+tc31qtJRtOetuNHMDT3NJ8rHU2wu3Qa2kfSU5nEr4frKqbR6zzVKylbZcDP5Xkfib/xXtFkt8fr9RTstbv5sGqevp/LB9hEsjzYi1texXw11W1UlV/B9wMXDZiradiLdlw8tt2d3qvobN8C/A1Jv+aPt3h/Y+PWOfV/MOTAV+YdtvuYY3tC/B+4J3d7Vjvth2xzsuZz5Nwa2of8N+BFw7j1wH/vrtN6/S9/CHgHiZ9v2FysvFXutt0su1bte51/MOTcCedK+0NXuMf6womZ/i/CvzWMO8XgV8cxsPk4e9fBb4MLB9v23kbTrV9wMuY/NfnbmD/MFzR3Z71+uxWvcdcBvA6fDd3AvuGz++/Alu727OObXsbcB9wAPgA8F3d7TmF9v0jJke7jwHfGMaffaxtjzd4K7IkNdnIfcCStKEZwJLUxACWpCYGsCQ1MYAlqYkBrIWU5HXDU7meSrJpfzhS880A1qI6APw08JnuQrS4On6WXpqpJP8G+HkmD0p5FLizqq4flnWWpgVnAGtTG7oXfobJE+G2AHcB8/wgHy0QA1ib3cuAj1fV/wVI8snmeqS/Zx+wNjv7GDS3DGBtdp8F/mmSM4fnI7+6uyDpaT6MR5tekuuAq4CvM/m1iU8zORn3u8ASkyda7a+qH28qUQvKANaml+Tsqvpmku9mctnZ7hp+M0/q5Ek4LYI9SS4GzgT2Gr6aFx4BS1ITT8JJUhMDWJKaGMCS1MQAlqQmBrAkNfl/v/spWIQCBJUAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 360x360 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAWEAAAFgCAYAAABqo8hyAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8li6FKAAASAUlEQVR4nO3df4wc9X3G8eeBw3EDJDHlcK3ruQ4porGiBNBBqUFVKEpkaBtDS0IRIpZCa1BDBc0PlQZVRaoipS0hUX+IYn4IJ6KUpBhhVEriUgRCgMvZcoyRCYQIirFrn0kaqFI1Nf70jx2L7eXOt7u33/ns7bxf0mp358fOc+O5x3OzO7OOCAEAchyVHQAAmowSBoBElDAAJKKEASARJQwAiUayA3Ri9erV8fDDD2fHAIAjcS8zLYg94QMHDmRHAIAiFkQJA8CwooQBIBElDACJKGEASEQJA0AiShgAElHCAJCIEgaARJQwACSihAEgUbEStj1u+1Hbu2w/Z/vaaviNtl+zvb26XVgqAwAMupIX8Dko6bMRsc328ZK22t5cjftKRNxUcNkAsCAUK+GI2Ctpb/X4Tdu7JI2VWh4ALES1HBO2vULS6ZK2VIOusb3D9p22l8wyzzrbk7Ynp6am6og5dMbGl8t2V7ex8eXZsYFGcelvW7Z9nKTHJH0xIjbaXirpgKSQ9GeSlkXEp470GhMTEzE5OVk05zCyrUtvfbKree69apX4Bm6gJ4N3PWHbx0i6T9LdEbFRkiJiX0S8FRGHJN0m6aySGQBgkJX8dIQl3SFpV0Tc3DZ8WdtkF0vaWSoDAAy6kp+OOEfSFZKetb29GvYFSZfZPk2twxEvS7qqYAYAGGglPx3xhGY+RvJQqWUCwELDGXMAkIgSBoBElDAAJKKEASARJQwAiShhAEhECeP/O2qE600ANSp5sgYWokMHe7reBIDesCcMAIkoYQBIRAkDQCJKGAASUcIAkIgSBoBElDAAJKKEASARJQwAiShhAEhECQNAIkoYABJRwgCQiBIGgESUMAAkooQBIBElDACJKGEASEQJA0AiShgAElHCAJCIEgaARJQwACSihAEgESUMAIkoYQBIRAkDQCJKGAASUcIAkIgSBoBElDAAJKKEASARJQwAiShhAEhECQNAIkoYABJRwgCQiBIGgESUMAAkooQBIBElDACJipWw7XHbj9reZfs529dWw0+wvdn2i9X9klIZAGDQldwTPijpsxHxfklnS/q07ZWSrpf0SEScIumR6jkANFKxEo6IvRGxrXr8pqRdksYkrZG0oZpsg6SLSmUAgEFXyzFh2ysknS5pi6SlEbFXahW1pJPqyAAAg6h4Cds+TtJ9kq6LiDe6mG+d7Unbk1NTU+UCAkCioiVs+xi1CvjuiNhYDd5ne1k1fpmk/TPNGxHrI2IiIiZGR0dLxgSANCU/HWFJd0jaFRE3t43aJGlt9XitpAdKZQCAQTdS8LXPkXSFpGdtb6+GfUHSlyR9w/aVkv5d0scLZgCAgVashCPiCUmeZfT5pZYLAAsJZ8wBQCJKGAASUcIAkIgSBoBElDAAJKKEASARJQwAiShhAEhECQNAIkoYABJRwgCQiBIGgESUMAAkooQBIBElDACJKGEASEQJA0AiShgAElHCAJCIEgaARJQwACSihAEgESUMAIkoYQBIRAkDQCJKGAASUcIAkIgSBoBElDAAJKKEASARJQwAiShhAEhECQNAIkoYABJRwgCQiBIGgESUMAAkooQBIBElDACJKGEASEQJA0AiShgAElHCAJCIEgaARJQwACSihAEgESUMAIkoYQBIRAkDQCJKGAASFSth23fa3m97Z9uwG22/Znt7dbuw1PIBYCEouSd8l6TVMwz/SkScVt0eKrh8ABh4xUo4Ih6X9INSrw8AwyDjmPA1tndUhyuWzDaR7XW2J21PTk1N1ZkPAGpTdwnfIul9kk6TtFfSl2ebMCLWR8REREyMjo7WlQ8AalVrCUfEvoh4KyIOSbpN0ll1Lh8ABk2tJWx7WdvTiyXtnG1aAGiCkVIvbPseSR+WdKLt3ZL+VNKHbZ8mKSS9LOmqUssHgIWgWAlHxGUzDL6j1PIAYCHijDkASEQJA0AiShgAElHCAJCooxK2fU4nwwAA3el0T/ivOxwGAOjCET+iZvtXJK2SNGr7M22j3iXp6JLBAKAJ5vqc8CJJx1XTHd82/A1Jl5QKBQBNccQSjojHJD1m+66IeKWmTADQGJ2eMfcO2+slrWifJyJ+rUQoAGiKTkv4m5L+TtLtkt4qFwcAmqXTEj4YEbcUTQIADdTpR9QetP37tpfZPuHwrWgyAGiATveE11b3n28bFpJO7m8cAGiWjko4It5bOggANFFHJWz7kzMNj4iv9TcOADRLp4cjzmx7vFjS+ZK2SaKEAWAeOj0c8Qftz22/W9LXiyQCgAbp9VKWP5Z0Sj+DAEATdXpM+EG1Pg0htS7c835J3ygVCgCaotNjwje1PT4o6ZWI2F0gDwA0SkeHI6oL+Tyv1pXUlkj6SclQANAUnX6zxick/Zukj0v6hKQttrmUJQDMU6eHI26QdGZE7Jck26OS/kXSP5YKBgBN0OmnI446XMCV17uYFwAwi073hB+2/S1J91TPL5X0UJlIANAcc33H3C9KWhoRn7f9W5LOlWRJT0m6u4Z8ADDU5jqk8FVJb0pSRGyMiM9ExB+qtRf81dLhAGDYzVXCKyJix/SBETGp1lcdAQDmYa4SXnyEcT/TzyAA0ERzlfAztn9v+kDbV0raWiYSADTHXJ+OuE7S/bYv19ulOyFpkaSLSwYDgCY4YglHxD5Jq2yfJ+kD1eB/ioh/LZ4MABqg0+sJPyrp0cJZAKBxOOsNABJRwgCQiBIGgESUMAAkooQBIBElDACJKGEASEQJA0AiShgAElHCAJCIEgaARJQwACSihAEgESUMAIkoYQBIVKyEbd9pe7/tnW3DTrC92faL1f2SUssHgIWg5J7wXZJWTxt2vaRHIuIUSY9UzwGgsYqVcEQ8LukH0wavkbSherxB0kWllg8AC0Hdx4SXRsReSaruT6p5+QAwUAb2jTnb62xP2p6cmprKjgMARdRdwvtsL5Ok6n7/bBNGxPqImIiIidHR0doCAkCd6i7hTZLWVo/XSnqg5uUDwEAp+RG1eyQ9JelU27ttXynpS5I+YvtFSR+pngNAY42UeuGIuGyWUeeXWiYALDQD+8YcADQBJQwAiShhAEhECQNAIkoYABJRwgCQiBIGgESUMAAkooQBIBElDACJKGEASEQJA0AiShgAElHCAJCIEgaARJQwACSihAEgESUMAIko4QVibHy5bHd1GzbdroOx8eXZkYE5FfuOOfTXnt2v6tJbn+xqnnuvWlUoTY5u18Gw/fwYTuwJA0AiShgAElHCAJCIEgaARJQwACSihAEgESUMAIkoYQBIRAkDQCJKGAASUcIAkIgSBoBElDAAJKKEASARJQwAiShhAEhECQNAIkoYABJRwgCQiBIGgESUMAAkooQBINHQlvDY+HLZ7uo2Nr48OzaAhhnJDlDKnt2v6tJbn+xqnnuvWlUoDQDMbGj3hAFgIaCEASARJQwAiShhAEhECQNAIkoYABKlfETN9suS3pT0lqSDETGRkQMAsmV+Tvi8iDiQuHwASMfhCABIlFXCIenbtrfaXjfTBLbX2Z60PTk1NVVzvM5xerSko0a6XgcjixZ3PQ8wjLIOR5wTEXtsnyRps+3nI+Lx9gkiYr2k9ZI0MTERGSE7wenRkg4d7GkdNH69AUraE46IPdX9fkn3SzorIwcAZKu9hG0fa/v4w48lfVTSzrpzAMAgyDgcsVTS/dUxvhFJfx8RDyfkAIB0tZdwRHxf0ofqXi4ADCI+ogYAiShhAEhECQNAIkoYABJRwgCQiBIGgERD+23LPamugQAAdaGE2/V4DQQA6BWHIwAgESUMAIkoYQBIRAkDQCJKGAASUcIAkIgSBoBElDAAJKKEASARJQwAiThtOQPXqABQoYQzcI0KABUORwBAIkoYABJRwgCQiBIGgESUMAAkooQBIBElDACJKGEASEQJA0AiShiYp7Hx5bLd1W1sfHl2bAwITlsG5mnP7lc5DR09Y08YABJRwgCQiBIGgESUMAAkooQBIBElDACJKGEASEQJA0AiShgAElHCAJCIEsbwOmqk62s6jCxa3PU8dRm2a1R0+/P08rMshHXGtSMwvA4d7OmaDoN6HYhhu0ZFtz9PLz/LQlhn7AkDQCJKGAASUcIAkIgSBoBElDAAJKKEASARJQwAiVJK2PZq29+1/T3b12dkAIBBUHsJ2z5a0t9KukDSSkmX2V5Zdw4AGAQZe8JnSfpeRHw/In4i6R8krUnIAQDpHBH1LtC+RNLqiPjd6vkVkn45Iq6ZNt06Seuqp6dK+m6tQWd2oqQD2SGmIdPcBi2PNHiZBi2PNHiZ5spzICJWd/uiGdeOmOmKJz/1P0FErJe0vnycztmejIiJ7BztyDS3QcsjDV6mQcsjDV6mUnkyDkfsljTe9vznJe1JyAEA6TJK+BlJp9h+r+1Fkn5H0qaEHACQrvbDERFx0PY1kr4l6WhJd0bEc3Xn6NFAHR6pkGlug5ZHGrxMg5ZHGrxMRfLU/sYcAOBtnDEHAIkoYQBI1OgSnuv0abf8VTV+h+0zquHjth+1vcv2c7avbZvnRtuv2d5e3S4snaca97LtZ6tlTrYNP8H2ZtsvVvdLalpHp7atg+2237B9XQ3r6JdsP2X7f2x/rpN5a1hHM2YqtR3NJ1M1ru/b0jzWUZHtqMNMl1fb9A7bT9r+0Fzz9rSOIqKRN7XeFHxJ0smSFkn6jqSV06a5UNI/q/XZ5rMlbamGL5N0RvX4eEkvHJ5X0o2SPldnnmrcy5JOnOF1/0LS9dXj6yX9eV2Zpr3Of0j6hRrW0UmSzpT0xfZlHGneGtbRbJn6vh3NN1OJbWm+efq9HXWRaZWkJdXjC/T2739ft6Um7wl3cvr0Gklfi5anJb3H9rKI2BsR2yQpIt6UtEvSWFaeOV53jaQN1eMNki5KyHS+pJci4pUult1TnojYHxHPSPrfLuYtuo5my1RoO5pXpjn0up76ladf21GnmZ6MiB9WT59W65yGuebteh01uYTHJL3a9ny3fvoXYM5pbK+QdLqkLW2Dr6n+hLmziz/Z5psnJH3b9la3Tvk+bGlE7JVav/Rq7XF0qi/rSK3Pgt8zbVipddTLvKXX0Zz6uB31I1O/t6W+rCP1bzvqJdOVav3FN9e8Xa+jJpdwJ6dPH3Ea28dJuk/SdRHxRjX4Fknvk3SapL2SvlxTnnMi4gy1/mz6tO1f7XC5JTPJrRNyPibpm23jS66jEvMWfd0+b0f9yNTvbakf66if21FXmWyfp1YJ/1G383aiySXcyenTs05j+xi1fnHujoiNhyeIiH0R8VZEHJJ0m1p/uhTPExGH7/dLur9tufsOHx6o7vd3mGfemSoXSNoWEfsODyi8jnqZt/Q6mlWB7WjemQpsS/24VEE/t6OOM9n+oKTbJa2JiNc7mLfrddTkEu7k9OlNkj7plrMl/Sgi9tq2pDsk7YqIm9tnmHY89GJJO2vIc6zt46vlHyvpo23L3SRpbfV4raQHOswzr0xt4y/TtD8hC6+jXuYtvY5mVGg7mm+mEttSPy5V0M/tqKNMtpdL2ijpioh4ocN5u19HvbyzOCw3td7Zf0GtdzpvqIZdLenq6rHVugD9S5KelTRRDT9XrT8/dkjaXt0urMZ9vZp2R/UPsqyGPCer9Q7tdyQ9d3jeatzPSnpE0ovV/Ql1rKNq3DslvS7p3dNes+Q6+jm19lTekPSf1eN3zTZvTetoxkyltqN5ZiqyLc3z363v21GHmW6X9MO2f5vJI83b6zritGUASNTkwxEAkI4SBoBElDAAJKKEASARJQwAiShhNJLtv7T9fHXK6/2235OdCc1ECaOpNkv6QER8UK3Pe/5xch40VMZX3gO1sv0nki5X66IrByRtjYib2iZ5WtIlGdkAShhDzfaEpN9W6wplI5K2Sdo6bbJPSbq35miAJEoYw+9cSQ9ExH9Lku0H20favkHSQUl3J2QDKGEMvZkuO9gaYa+V9BuSzg/O30cS3pjDsHtC0m/aXlxdt/fXpdZ3hKl1fdiPRcSPMwOi2dgTxlCLiGdsb1LrqmCvSJqU9CNJfyPpHZI2t64oqacj4uq0oGgsrqKGoWf7uIj4L9vvlPS4pHVRfbcbkI09YTTBetsrJS2WtIECxiBhTxgAEvHGHAAkooQBIBElDACJKGEASEQJA0Ci/wP3MI02wdU8vQAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 360x360 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAWAAAAFgCAYAAACFYaNMAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8li6FKAAARO0lEQVR4nO3dfaxkBXnH8e8PFkQBK8aVrstu0JZYSZMCuVJcjFGpDWIr2qqUWKWpdjGV1vfGapraGBP/oGraNJZVqGiRYhUrWotaJBqDpSyUInR9F2Vhy96tUehL1IWnf8zQ3iz7Mrv3nnnuvfP9JJM7c2bmnmdvdr579syZc1NVSJKm77DuASRpVhlgSWpigCWpiQGWpCYGWJKarOkeYBJnn312XXvttd1jSNKhyt4Wrogt4F27dnWPIElLbkUEWJJWIwMsSU0MsCQ1McCS1MQAS1ITAyxJTQywJDUxwJLUxABLUhMDLElNBgtwkg1Jrk+yLckdSV4zXv62JHcnuXV8OWeoGSRpORvyZDy7gTdU1S1JjgVuTvK58X3vrqqLB1y3JC17gwW4qnYAO8bX70+yDVg/1PokaaWZyj7gJCcCpwI3jhddlOS2JJclOW4fz9mcZGuSrfPz89MYU6vE+g0bSTLoZf2Gjd1/TK0CGfq3Iic5BvgC8I6qujrJ8cAuoIC3A+uq6rf39z3m5uZq69atg86p1SMJ511yw6DruOrCTfgbxXUQpn8+4CRHAB8DrqiqqwGq6t6qeqCqHgTeB5w+5AyStFwNeRREgEuBbVX1rgXL1y142AuB24eaQZKWsyGPgjgTeBnwlSS3jpe9BTg/ySmMdkHcCVw44AyStGwNeRTEl9j7fo9PD7VOSVpJ/CScJDUxwJLUxABLUhMDLElNDLAkNTHAktTEAEtSEwMsSU0MsCQ1McCS1MQAS1ITAyxJTQywJDUxwJLUxABLUhMDLElNDLAkNTHAktTEAEtSEwMsSU0MsCQ1McCS1MQAS1ITAyxJTQywJDUxwJLUxABLUhMDLElNDLAkNTHA0qE4bA1JBr2s37Cx+0+pga3pHkBakR7czXmX3DDoKq66cNOg31/93AKWpCYGWJKaGGBJamKAJamJAZakJgZYkpoYYElqYoAlqYkBlqQmBliSmhhgSWpigCWpiQGWpCYGWJKaGGBJamKAJamJAZakJgZYkpoMFuAkG5Jcn2RbkjuSvGa8/LFJPpfkG+Ovxw01gyQtZ0NuAe8G3lBVTwHOAF6d5GTgzcB1VXUScN34tiTNnMECXFU7quqW8fX7gW3AeuBc4PLxwy4HXjDUDJK0nE1lH3CSE4FTgRuB46tqB4wiDTx+GjNI0nIzeICTHAN8DHhtVd13EM/bnGRrkq3z8/PDDShJTQYNcJIjGMX3iqq6erz43iTrxvevA3bu7blVtaWq5qpqbu3atUOOKUkthjwKIsClwLaqeteCu64BLhhfvwD4xFAzSNJytmbA730m8DLgK0luHS97C/BO4CNJXgF8D3jxgDNI0rI1WICr6ktA9nH3WUOtV5JWCj8JJ0lNDLAkNTHAktTEAEtSEwMsSU0MsCQ1McCS1MQAS1ITAyxJTQywJDUxwJLUxABLUhMDLElNDLAkNTHAktTEAEtSEwMsSU0MsCQ1McCS1MQAS1ITAyxJTQywJDUxwJLUxABLUhMDLElNDLAkNTHAktTEAEtSEwMsSU0MsCQ1McCS1MQAS1ITAyxJTQywJDUxwJLUxABLUhMDLElNDLAkNTHAktTEAEtSEwMsSU0MsCQ1McCS1MQAS1ITAyxJTQywJDUxwJLUxABLUhMDLElNDLAkNRkswEkuS7Izye0Llr0tyd1Jbh1fzhlq/ZK03A25BfwB4Oy9LH93VZ0yvnx6wPVL0rI2WICr6ovA94f6/pK00nXsA74oyW3jXRTH7etBSTYn2Zpk6/z8/DTnk6SpmHaA3wv8DHAKsAP40309sKq2VNVcVc2tXbt2WvNJ0tRMNcBVdW9VPVBVDwLvA06f5volaTmZaoCTrFtw84XA7ft6rCStdmuG+sZJrgSeCTwuyXbgj4FnJjkFKOBO4MKh1i9Jy91gAa6q8/ey+NKh1idJK42fhJOkJgZYkpoYYElqYoAlqclEAU5y5iTLJEmTm3QL+M8nXCZJmtB+D0NL8jRgE7A2yesX3PVo4PAhB5Ok1e5AxwEfCRwzftyxC5bfB7xoqKEkaRbsN8BV9QXgC0k+UFXfndJMkjQTJv0k3COSbAFOXPicqnr2EENJ0iyYNMB/C/wl8H7ggeHGkaTZMWmAd1fVewedRJJmzKSHoX0yye8mWZfksQ9dBp1Mkla5SbeALxh/fdOCZQU8aWnHkaTZMVGAq+qJQw8iSbNmogAnefnellfVB5d2HEmaHZPugnjqgutHAWcBtwAGWJIO0aS7IH5v4e0kPwV8aJCJJGlGHOrpKP8bOGkpB5GkWTPpPuBPMjrqAUYn4XkK8JGhhpKkWTDpPuCLF1zfDXy3qrYPMI8kzYyJdkGMT8rzVUZnRDsO+PGQQ0nSLJj0N2K8BPhn4MXAS4Abk3g6SklahEl3QbwVeGpV7QRIshb4R+CjQw0mSavdpEdBHPZQfMf+4yCeK0nai0m3gK9N8hngyvHt84BPDzOSJM2GA/1OuJ8Fjq+qNyX5NeDpQIAvA1dMYT5JWrUOtBvhPcD9AFV1dVW9vqpex2jr9z1DDydJq9mBAnxiVd2258Kq2sro1xNJkg7RgQJ81H7ue+RSDiJJs+ZAAb4pye/suTDJK4CbhxlJkmbDgY6CeC3w8SQv5f+DOwccCbxwyMEkabXbb4Cr6l5gU5JnAT8/Xvz3VfX5wSeTpFVu0vMBXw9cP/AskjRT/DSbJDUxwJLUxABLUhMDLElNDLAkNTHAktTEAEtSEwOsqVq/YSNJBr1IK8WkJ2SXlsQ92+/ivEtuGHQdV124adDvLy0Vt4AlqYkBlqQmBliSmhhgSWpigCWpiQGWpCaDBTjJZUl2Jrl9wbLHJvlckm+Mvx431Polabkbcgv4A8DZeyx7M3BdVZ0EXDe+LUkzabAAV9UXge/vsfhc4PLx9cuBFwy1fkla7qa9D/j4qtoBMP76+CmvX5KWjWX7JlySzUm2Jtk6Pz/fPY60Kk3j3BzrN2zs/mMuW9M+F8S9SdZV1Y4k64Cd+3pgVW0BtgDMzc3VtAaUZonn5ug17S3ga4ALxtcvAD4x5fVL0rIx5GFoVwJfBp6cZHuSVwDvBJ6T5BvAc8a3JWkmDbYLoqrO38ddZw21TklaSZbtm3CStNoZYElqYoAlqYkBlqQmBliSmhhgSWpigCWpiQGWpCYGWJKaGGBJamKAJamJAZakJgZYkpoYYElqYoAlqYkBlqQmBliSmhhgSWpigCWpiQGWpCYGWJKaGGBJamKAJamJAZakJgZYkpoYYElqYoAlqYkBlqQmBliSmhhgSWpigCWpiQGWpCYGWJKaGGBJamKAJamJAZakJgZYkpoYYElqYoAlqYkBlqQmBliSmhhgSWqypnuAIa3fsJF7tt816DoOP+IRPPCTHw26jiecsIG77/reoOuYxs9KB+mwNSTpnkIDWtUBvmf7XZx3yQ2DruOqCzdNZR1Dm8bPCqbzZ1k1Hty9Kv5uad/cBSFJTQywJDUxwJLUxABLUhMDLElNDLAkNWk5DC3JncD9wAPA7qqa65hDkjp1Hgf8rKra1bh+SWrlLghJatIV4AI+m+TmJJv39oAkm5NsTbJ1fn5+yuNJ0vC6AnxmVZ0GPBd4dZJn7PmAqtpSVXNVNbd27drpTyhJA2sJcFXdM/66E/g4cHrHHJLUaeoBTnJ0kmMfug78MnD7tOeQpG4dR0EcD3x8fJq9NcCHq+rahjkkqdXUA1xV3wZ+YdrrlaTlxsPQJKmJAZakJgZYkpoYYElqYoAlqYkBlqQmBliSmhhgSWpigCWpiQGWpCYGWJKaGGBJamKAJamJAZakJgZYkpoYYElqYoAlqYkBlqQmBnglOGwNSQa9SCvd+g0bB3+drN+wcUln7vilnDpYD+7mvEtuGHQVV124adDvLw3tnu13rbjXiVvAktTEAEtSEwMsSU0MsCQ1McCS1MQAS1ITAyxJTQywJDUxwJLUxE/CSRrW+KP0ejgDLGlYU/goPazMj9O7C0KSmhhgSWpigCWpiQGWpCYGWJKaGGBJamKAJamJAZakJgZYkpoYYElqYoAlqYkBlqQmBliSmhhgSWpigCWpiQGWpCYGWJKaGGBJamKAJalJS4CTnJ3ka0m+meTNHTNIUrepBzjJ4cBfAM8FTgbOT3LytOeQpG4dW8CnA9+sqm9X1Y+BvwHObZhDklqlqqa7wuRFwNlV9crx7ZcBv1hVF+3xuM3A5vHNJwNfm+KYjwN2TXF9S2Wlzg3O3sXZp2NXVZ2958I1DYNkL8se9q9AVW0Btgw/zsMl2VpVcx3rXoyVOjc4exdn79WxC2I7sGHB7ROAexrmkKRWHQG+CTgpyROTHAn8BnBNwxyS1GrquyCqaneSi4DPAIcDl1XVHdOe4wBadn0sgZU6Nzh7F2dvNPU34SRJI34STpKaGGBJajJTAT7QR6Az8mfj+29Lctoe9x+e5F+SfGp6U//fug959iSPSfLRJF9Nsi3J01bQ7K9LckeS25NcmeSoZTb7zyX5cpIfJXnjwTx3SIc6d5INSa4f/z25I8lrpjn3eIZD/pmP7297nR60qpqJC6M3/L4FPAk4EvhX4OQ9HnMO8A+MjlU+A7hxj/tfD3wY+NRKmh24HHjl+PqRwGNWwuzAeuA7wCPHtz8C/NYym/3xwFOBdwBvPJjnLtO51wGnja8fC3x9WnMvdvYF97e8Tg/lMktbwJN8BPpc4IM18k/AY5KsA0hyAvA84P3THHrskGdP8mjgGcClAFX146r6wUqYfXzfGuCRSdYAj2K6x4wfcPaq2llVNwE/OdjnDuiQ566qHVV1y/j6/cA2Rv8QTstifubdr9ODNksBXg/cteD2dh7+F2t/j3kP8AfAg0MNuB+Lmf1JwDzwV+P/lr0/ydFDDjvhXAd8TFXdDVwMfA/YAfywqj474Kx7mmT2IZ67WEuy7iQnAqcCNy7JVJNZ7Oydr9ODNksBnuQj0Ht9TJJfAXZW1c1LP9ZEDnl2RluQpwHvrapTgf8Cprk/cjE/9+MYbf08EXgCcHSS31zi+fZnoo/ND/DcxVr0upMcA3wMeG1V3bckU0246r0sm2j2ZfA6PWizFOBJPgK9r8ecCTw/yZ2M/kv07CR/PdyoD7OY2bcD26vqoa2YjzIK8rQsZvZfAr5TVfNV9RPgamDTgLPuaTEfm+/8yP2i1p3kCEbxvaKqrl7i2Q5kMbN3v04P2iwFeJKPQF8DvHz8rvwZjP7Lu6Oq/rCqTqiqE8fP+3xVTXNLbDGz/ztwV5Injx93FvBvU5t8EbMz2vVwRpJHJcl49m3LbPYhnrtYh7zu8c/5UmBbVb1rwBn35ZBnXwav04PX/S7gNC+M3m3/OqN3Wd86XvYq4FXj62F0svhvAV8B5vbyPZ5Jw7uri5kdOAXYCtwG/B1w3Aqa/U+ArwK3Ax8CHrHMZv9pRltt9wE/GF9/9L6eu9znBp7O6L/8twG3ji/nrITZ9/geLa/Tg734UWRJajJLuyAkaVkxwJLUxABLUhMDLElNDLAkNTHAmnlJ3j4+C9utST6b5AndM2k2eBiaZl6SR9f447ZJfp/R2bde1TyWZkDHr6WX2iT5I+CljE74sgu4uaouXvCQo5neORs04wywZkaSOeDXGZ3haw1wC3Dz+L53AC8Hfgg8q2tGzRb3AWuWPB34RFX9T43OdfvJh+6oqrdW1QbgCuCirgE1WwywZsneTnW4pw8z2kqWBmeANUu+BPxqkqPG57t9HkCSkxY85vmMTv4jDc59wJoZVXVTkmsY/Z6x7zI6Q9wPgXeOT9f54Hi5R0BoKjwMTTMlyTFV9Z9JHgV8Edhc49+BJk2bW8CaNVuSnAwcBVxufNXJLWBJauKbcJLUxABLUhMDLElNDLAkNTHAktTkfwFlFrcBG1GluwAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 360x360 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "sns.displot(df['g1'])\n",
    "sns.displot(df['g2'])\n",
    "sns.displot(df['g3'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "}"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
